### ISSUE TITLE
Issue not necessarily related to the fork, but the entire project.

### ISSUE THREAD

**Issue by FUCKYOUGITHUBFUCKYOU** [chaun14/invite-manager-bot#15]
Hey, so I'm unable to run it.

`npm run dev`
Gives 
`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/rest/RequestHandler' is not defined by "exports" in /root/invite-manager-bot/node_modules/eris/package.json`

Which is related to the import used here https://github.com/chaun14/invite-manager-bot/blob/master/src/framework/RequestHandler.ts#L4

Seems like other users have found issue with this as well, https://stackoverflow.com/questions/63951163/error-err-package-path-not-exported-package-subpath-lib-rest-requesthandl , but the answers given to this issue seem completely unrelated.

Anyway, if you have an idea how to resolve this, please let me know.

tested on multiple Node | npm versions, doesn't seem to make a difference. currently running the latest versions of both.

**Comment by chaun14** [comment]
the way to fix is explained there https://github.com/SideProjectGuys/invite-manager-bot/issues/167#issuecomment-684043572

**Comment by FUCKYOUGITHUBFUCKYOU** [comment]
Will try this, thanks.
