### ISSUE TITLE
manager shows shard undefined log

### ISSUE THREAD

**Issue by ThisDudeBoy** [chaun14/invite-manager-bot#18]
[https://media.discordapp.net/attachments/832354283907055657/832358258463211555/unknown.png?width=594&height=676](Screen)
Edited the status and i have it.

**Comment by chaun14** [comment]
Which command are you using to start the bot?

**Comment by ThisDudeBoy** [comment]
Your manager

**Comment by chaun14** [comment]
And which config have you set in the controller part of the [config.json](https://github.com/chaun14/invite-manager-bot/blob/master/config.example.json#L71) file ?

**Comment by ThisDudeBoy** [comment]
`{	
	"devToken": "MainTOKEN",
	"sentryDsn": "",
	"bot": {
		"dbPrefix": "im",
		"type": "regular",
		"embedColor": "00cbeb",
		"activity": {
			"status": "dnd",
			"message": "docs.invite-manager.co !",
			"type": "streaming",
			"url": "https://www.twitch.tv/arftnl"
		},
		"links": {
			"add": "",
			"support": "",
			"website": "",
			"patreon": ""
		},
		"dm": {
			"guild": "",
			"channel": ""
		},
		"apiAuth": {
			"username": "",
			"password": ""
		},
		"dblToken": null,
		"music": {
			"pollyUrl": ""
		}
	},
	"rabbitmq": {
		"hostname": "localhost",
		"username": "guest",
		"password": "guest",
		"prefix": ""
	},
	"databases": [
		{
			"host": "IP",
			"port": 3306,
			"user": "root",
			"password": "rootpass",
			"range": {
				"from": 0,
				"to": 0
			}
		},
		{
			"host": "IP",
			"port": 3306,
			"user": "root",
			"password": "rootpass",
			"range": {
				"from": 1,
				"to": 1
			}
		}
	],
	"controller": {
		"botToken": "Second Token",
		"shardCount": 1,
		"owners": ["MYID", "FRIENDID"],
		"incidentChannel": "INCIDENTCHANNELID",
		"firstDebugPort": 40000
	}
}
`


The bot work well.
Only log are undefined

**Comment by chaun14** [comment]
The manages isn't made to run with only a shard. If you need to run it with only a shard just use the `npm run dev` command.

You should try to set like 2 shards if the problem still occurs.

**Comment by ThisDudeBoy** [comment]
> The manages isn't made to run with only a shard. If you need to run it with only a shard just use the `npm run dev` command.
> 
> You should try to set like 2 shards if the problem still occurs.

no no but with no edit code, the bot worked fine. With [SHARD ID] but now is undefined maybe i edited client.ts where is defined [SHARD ID] ?

**Comment by chaun14** [comment]
The manager doesn't interact with the client. The undefined that you're seeing is from [this line](https://github.com/chaun14/invite-manager-bot/blob/master/index.js#L69)

**Comment by ThisDudeBoy** [comment]
i don't edited nothing here dude

**Comment by ThisDudeBoy** [comment]
![image](https://user-images.githubusercontent.com/56303464/114939145-5371e200-9e40-11eb-95fb-ed2ef4fb3e39.png)
![image](https://user-images.githubusercontent.com/56303464/114939163-579dff80-9e40-11eb-887e-97d4be701763.png)

**Comment by chaun14** [comment]
Yes ik, it seems to be a problem caused by the single shard config, the manage is made to manage multiple shards, not only one.

**Comment by ThisDudeBoy** [comment]
> Yes ik, it seems to be a problem caused by the single shard config, the manage is made to manage multiple shards, not only one.

2 shards same issue

**Comment by chaun14** [comment]
oh it could also be a problem with the dependency "colors" which doesn't work perfectly or isn't working with your cmd/ssh client/terminal

**Comment by ThisDudeBoy** [comment]
Woked on hours later.

**Comment by ThisDudeBoy** [comment]
Ohh fixed thank you 

For other people : color module issue 👯
