### ISSUE TITLE
Shards are stuck on "loading"

### ISSUE THREAD

**Issue by KiwiTerra** [chaun14/invite-manager-bot#4]
Logs: https://hasteb.in/tigusifi.log
Configuration: https://hasteb.in/hibegazo.json
Output on discord:
![image](https://user-images.githubusercontent.com/26503509/98990994-82032e00-252b-11eb-8825-23f64e10619d.png)

**Comment by chaun14** [comment]
The bot takes few minutes to begin the server fetching. It depends of the connection. Just wait and it should start

**Comment by Kazzox-web** [comment]
Hey, @chaun14 i have the same problem. Infinity "Loading"...

**Comment by chaun14** [comment]
have you enabled all gateway intents on your bots?

**Comment by KiwiTerra** [comment]
Yes

**Comment by Kazzox-web** [comment]
Yes, don't work.

**Comment by KiwiTerra** [comment]
It's working with `npm run dev` (no sharding) but it's not working with `npm start`

**Comment by chaun14** [comment]
That haven't any senses cuz `npm run dev` and the sharding controller has the same launch system

**Comment by Kazzox-web** [comment]
The bot work without shard controller.
![image](https://user-images.githubusercontent.com/74381822/99116229-f1dceb80-25f3-11eb-84e9-663ab61853c2.png)

With controller, loading infinitly
![image](https://user-images.githubusercontent.com/74381822/99116254-fef9da80-25f3-11eb-9495-c9dfe3743900.png)


Gateway intents activated

**Comment by chaun14** [comment]
Use the dev mode for the moment. I'll check that later

**Comment by Kazzox-web** [comment]
Yes thanks you, try yourself you will see.

**Comment by chaun14** [comment]
That's because you've set two shards (max 5000 servers) but your bot has only few server. To avoid this issue, set a correct shard count (1 for under 100 servers)
