### ISSUE TITLE
Leaves SQL table not populating

### ISSUE THREAD

**Issue by j-b-hunter** [chaun14/invite-manager-bot#8]
Users that leave are not being added to the leave table in sql. all the other tables update properly.

This allows users to leave and rejoin and not be removed and just keep adding invites to a user.

**Comment by chaun14** [comment]
Are there an error in the console ?

**Comment by j-b-hunter** [comment]
No errors.

> Are there an error in the console ?

**Comment by j-b-hunter** [comment]
Never mind, its working now. Just cleared the dbs and reupped the script again
